apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: microservices
build:
  artifacts:
    - image: order
      context: order-service
      docker:
        dockerfile: Dockerfile
    - image: payment
      context: payment-service
      docker:
        dockerfile: Dockerfile
    - image: shipping
      context: shipping-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - jaeger/deployment.yaml
    - prometheus/deployment.yaml
    - mysql/deployment.yaml
    - order-service/deployment.yaml
    - payment-service/deployment.yaml
    - shipping-service/deployment.yaml
deploy:
  kubectl: {}
  kubeContext: kind-microservices
